### ISSUE TITLE
anisotropy-guided filtering

### ISSUE THREAD

**Issue by ChenweiHuang-gpu** [fergaletto/deep_defocus_classification#1]
Hello, I tried to use the anisotropy-guided filtering part in your code, but the result is not consistent with what I imagined, and the calculation of weight w and gamma in the code does not seem to be the calculation of the original paper way, is it convenient to answer

**Comment by fergaletto** [comment]
Hi, The anisotropic guided filter is not used to refine the blur map. It is only implemented in the file WeigtedGF.m but not used at all for this project. I suggest you ignore it. However, you can refer to equation 20 in the paper to see how i calculate the weights.
